apiVersion: v1
kind: PersistentVolume
metadata:
  name: sftpgo-pv
  namespace: sftp
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/srv/sftpgo/data"  # Path on the host machine
